kversion: '3.1'

services:

  redmine:
    image: redmine:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: passwd1234
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd1234
      MYSQL_DATABASE: redmine
