# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.0.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-19T12:48:16Z"
  labels:
    app: bookmedik
  name: bookmedik
spec:
  containers:
  - command:
    - /usr/local/bin/script.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: DATABASE_USER
      value: bookmedik
    - name: DATABASE_PASSWORD
      value: bookmedik
    - name: DATABASE_HOST
      value: 127.0.0.1
    - name: APACHE_SERVER_NAME
      value: www.bookmedik-francisco.org
    image: localhost/bookmedik-podman
    name: bookmedik-app
    ports:
    - containerPort: 80
      hostPort: 8082
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  - args:
    - mysqld
    command:
    - docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: GPG_KEYS
      value: 177F4010FE56CA3336300305F1656F24C74CD1D8
    - name: MARIADB_MAJOR
      value: "10.5"
    - name: MARIADB_VERSION
      value: 1:10.5.10+maria~focal
    - name: MYSQL_USER
      value: bookmedik
    - name: MYSQL_ROOT_PASSWORD
      value: franciscojavier
    - name: MYSQL_DATABASE
      value: bookmedik
    - name: MYSQL_PASSWORD
      value: bookmedik
    - name: GOSU_VERSION
      value: "1.12"
    image: docker.io/library/mariadb:latest
    name: mysql-wp
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  dnsConfig: {}
  restartPolicy: Always
status: {}
